#spring:
#  datasource:
#    url: jdbc:postgresql://0.0.0.0:5432/alfa_battle
#    username: alfa_battle
#    password: qwe123
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    show-sql: true
#    database: postgresql
#    hibernate:
#      ddl-auto: none
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    properties:
#        format_sql: true
server:
  port: 8084